version: '3'

services:
    node:
        build: .
        depends_on:
            - mongo
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./:/usr/src/app:rw
        working_dir: /usr/src/app
        env_file:
            - .env

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db:rw

volumes:
    mongo-data: {}
